name: Push to docker registry
on:
  release:
    types:
      - released

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    env:
      DOCKER_REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}